### ISSUE TITLE
some icon replacements not saved when bulk replacing

### ISSUE THREAD

**Issue by ghost** [ezeek/smartly#10]

**Comment by ezeek** [comment]
TESTING
- create new dash, add 6+ of the same tile type (window) and a handful of other types that would have other options (motion).   BACKUP FOR FUTURE USE
- update with smartly, change icons for all 6+ of the same type, re-update.  
- check if all icon replacements were saved
--
- USE BACKUP
- update with smartly, change icons for all 6+ of the same type, then change icons for other types.  re-update.  
- check if all icon replacements were saved
-- 
repeat with other options until it fails to save an icon replacement

**Comment by ezeek** [comment]
this was an issue relating to icon value recall.. it would select the icon based on saved value, but would fail to actually set the value of the hidden value field.
