### ISSUE TITLE
Add "iPad and iPad Air" to calibration 

### ISSUE THREAD

**Issue by TechMedX** [ezeek/smartly#50]
iPad Air 1024x666 👿 

768x922

**Comment by TechMedX** [comment]
removed

**Comment by TechMedX** [comment]
iPad (5th Gen) - 1024x659

I cannot get portrait (it is mounted in the wall, not removing it)

**Comment by ezeek** [comment]
iPad Air 768x1024
iPad (5th Gen) 768x1024

**Comment by ezeek** [comment]
rolled out to https://hubitat.ezeek.us/dev/smartly/
