### ISSUE TITLE
Add calibration for Android Essential PH-1

### ISSUE THREAD

**Issue by ezeek** [ezeek/smartly#75]
@codahq I'd like to add your device to the built-in calibrations.  Could you visit https://whatismyviewport.com with a full screen browser (or record the values for both portrait and landscape in any browser) and post them in here?  Thanks!

**Comment by codahq** [comment]
Sure, thank you. 439×702 reported by whatismyviewport.com.

**Comment by ezeek** [comment]
hot-patched in v1.06, using fuzzy 437-442 x 853-858.  viewport subtracts vertical real estate for addressbar, statusbar.
