### ISSUE TITLE
HSM and Mode tiles have no options

### ISSUE THREAD

**Issue by TechMedX** [ezeek/smartly#85]
Reported by - @temptingtime

Post - https://community.hubitat.com/t/smartly-bug-report-and-support-thread/49292/126

![image](https://user-images.githubusercontent.com/42358953/92279295-f8006e80-eec4-11ea-90ee-6ca3b735a773.png)

No Zoomable, borders, colors etc.

If they should not have options could a message be added?

**Comment by ezeek** [comment]
they should have zoomable, borders and colors.  I'm on it!
